### ISSUE TITLE
Assignment 2: Grid Image Search - Ready for Review

### ISSUE THREAD

**Issue by sbharech** [sbharech/AndroidGoogleImageSearch#4]
My app is complete and ready for review. Kindly review it and let me know your comments. /cc @codepathreview @codepath

-- Suraj Bharech (observer)

**Comment by nesquena** [comment]
:+1: Nice job Suraj, great to see you were able to get in a number of optionals too and improve the UI! I have provided a detailed [Project 2 Feedback Guide here](http://courses.codepath.com/snippets/intro_to_android/project_2_feedback) which covers the most common issues with this submitted project. Read through the feedback guide point-by-point to determine how you could improve your submission. 

Let us know if you have any other thoughts or questions about this project. The next project (Twitter Client) will be very important since it introduces the majority of the remaining pieces necessary to build a fully functional API client with complex feeds of data and user creation.
